[tool.poetry]
name = "farmtech"
version = "0.1.0"
description = "Consolidação Fase 7 - FarmTech"
authors = ["Guilherme <you@example.com>"]

[tool.flake8]
max-line-length = 88
exclude = .git,__pycache__,venv

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
